### ISSUE TITLE
能下載但無法開啟

### ISSUE THREAD

**Issue by jay7895214** [qinlili23333/HyReadDownloader#7]
您好，偶然找到了 HyReadEPUBV2 這個腳本，使用時可以順利下載，但用 calibre 開啟 epub 時卻出現了下列錯誤訊息；
感覺是個相當好用的腳本，期待修復，謝謝您！
開啟失敗的 epub ：[Online Reader (1).zip](https://github.com/qinlili23333/HyReadDownloader/files/13050935/Online.Reader.1.zip)

```
calibre, version 6.2.1
錯誤： 載入書本失敗: 無法開啟在 D:\(省略).epub 的書籍，請點選 「顯示詳細資料」查看更多資訊。

Failed to convert book: D:\(省略).epub with error:
WARNING: Epub doesn't contain a valid mimetype declaration
InputFormatPlugin: EPUB Input running
on D:\(省略).epub
Found HTML cover OEBPS/cover.xhtml
Failed to parse as XML, parsing as tag soup
Failed to parse as XML, parsing as tag soup
Failed to parse as XML, parsing as tag soup
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 196, in main
  File "<string>", line 1, in <module>
  File "calibre\srv\render_book.py", line 823, in viewer_main
  File "calibre\srv\render_book.py", line 814, in render_for_viewer
  File "calibre\srv\render_book.py", line 792, in render
  File "calibre\srv\render_book.py", line 607, in process_exploded_book
  File "calibre\ebooks\oeb\polish\toc.py", line 303, in get_toc
  File "calibre\ebooks\oeb\polish\toc.py", line 289, in get_x_toc
  File "calibre\ebooks\oeb\polish\toc.py", line 165, in parse_ncx
  File "calibre\ebooks\oeb\polish\container.py", line 624, in parsed
  File "calibre\ebooks\oeb\polish\container.py", line 595, in parse
  File "calibre\ebooks\oeb\polish\container.py", line 189, in parse_xml
  File "calibre\utils\xml_parse.py", line 35, in safe_xml_fromstring
  File "src/lxml/etree.pyx", line 3254, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1913, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1800, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1141, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1
```

**Comment by IntBoat** [comment]
HyRead 似乎改變了加密方式，無法使用了。Get Outlook for AndroidFrom: Jay ***@***.***>Sent: Friday, October 20, 2023 3:06:00 PMTo: qinlili23333/HyReadDownloader ***@***.***>Cc: Subscribed ***@***.***>Subject: [qinlili23333/HyReadDownloader] 能下載但無法開啟 (Issue #7)
您好，偶然找到了 HyReadEPUBV2 這個腳本，使用時可以順利下載，但用 calibre 開啟 epub 時卻出現了下列錯誤訊息；
感覺是個相當好用的腳本，期待修復，謝謝您！
開啟失敗的 epub ：Online Reader (1).zip
calibre, version 6.2.1
錯誤： 載入書本失敗: 無法開啟在 D:\(省略).epub 的書籍，請點選 「顯示詳細資料」查看更多資訊。

Failed to convert book: D:\(省略).epub with error:
WARNING: Epub doesn't contain a valid mimetype declaration
InputFormatPlugin: EPUB Input running
on D:\(省略).epub
Found HTML cover OEBPS/cover.xhtml
Failed to parse as XML, parsing as tag soup
Failed to parse as XML, parsing as tag soup
Failed to parse as XML, parsing as tag soup
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 196, in main
  File "<string>", line 1, in <module>
  File "calibre\srv\render_book.py", line 823, in viewer_main
  File "calibre\srv\render_book.py", line 814, in render_for_viewer
  File "calibre\srv\render_book.py", line 792, in render
  File "calibre\srv\render_book.py", line 607, in process_exploded_book
  File "calibre\ebooks\oeb\polish\toc.py", line 303, in get_toc
  File "calibre\ebooks\oeb\polish\toc.py", line 289, in get_x_toc
  File "calibre\ebooks\oeb\polish\toc.py", line 165, in parse_ncx
  File "calibre\ebooks\oeb\polish\container.py", line 624, in parsed
  File "calibre\ebooks\oeb\polish\container.py", line 595, in parse
  File "calibre\ebooks\oeb\polish\container.py", line 189, in parse_xml
  File "calibre\utils\xml_parse.py", line 35, in safe_xml_fromstring
  File "src/lxml/etree.pyx", line 3254, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1913, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1800, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1141, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1
